FROM maven AS build
WORKDIR /app
COPY ./samplejavacode  /app

RUN mvn package

FROM tomcat
WORKDIR /myapp

COPY --from=build /app/target/*.war /usr/local/tomcat/webapps
EXPOSE 8080
CMD ["catalina.sh", "run"]


