FROM maven AS build

#RUN mkdir /gourav


COPY . .
WORKDIR /java-docker-build-tutorial
RUN mvn clean package

FROM eclipse-temurin:17-jre-alpine
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=build /java-docker-build-tutorial/target/app.jar .

EXPOSE 8123
ENTRYPOINT ["java", "-jar", "./app.jar"]

